export const emergence = {
  event: {
    wordmark: 'EMERGE',
    series: 'EMERGE SUMMIT',
    theme: 'Emergence',
    capsule: 'Beyond Limit',
    keywords: ['DISRUPTION', '1M+ GRANT', 'GROWTH', 'NETWORKING'],
    city: 'LAGOS',
    venue: 'UNILAG MAIN AUDITORIUM',
    time: '9 AM',
    timeNote: 'PROMPT',
    date: '15TH',
    dateNote: 'AUGUST 2026',
    ticketLabel: 'Get Ticket:',
    url: 'www.emerge.xyz',
    qrSrc: '',
    convenerLabel: 'CONVENER SLOT — Emerge',
  },
  size: {
    width: 1080,
    height: 1350,
  },
  colors: {
    navyDeep: '#061433',
    navy: '#0B1E6E',
    royal: '#102E8D',
    royalMid: '#1E42A3',
    cyanCard: '#5EB6FF',
    cyanCardDeep: '#3A8DFF',
    ink: '#FFFFFF',
    inkSoft: '#D7E6FF',
    lime: '#B6FF00',
    limeInk: '#0A1400',
    amber: '#FFB800',
    orange: '#FF8A3D',
    motifBlue: '#4DA1FF',
    grid: 'rgba(255,255,255,0.08)',
    slot: 'rgba(6, 20, 51, 0.35)',
  },
  fonts: {
    display: '"Orbitron", sans-serif',
    body: '"Manrope", sans-serif',
  },
  speakers: [
    { name: 'SPEAKER 01', title: 'Title / Role', accent: 'amber' },
    { name: 'SPEAKER 02', title: 'Title / Role', accent: 'orange' },
    { name: 'SPEAKER 03', title: 'Title / Role', accent: 'amber' },
  ],
  panelists: [
    { name: 'PANEL 01', title: 'Panelist', accent: 'cyan' },
    { name: 'PANEL 02', title: 'Panelist', accent: 'amber' },
    { name: 'PANEL 03', title: 'Panelist', accent: 'orange' },
  ],
}
