import MindCanGoQuote from '../../fliers/royal-prince/MindCanGoQuote'
import { createProject } from '../layout'

/** Royal Prince — personal quote / thought leadership boards */
export default createProject({
  id: 'royal-prince',
  name: 'Royal Prince',
  brand: 'Royal Prince',
  description: 'Personal quote posters — void-profile-ask system.',
  color: '#d8d8d8',
  fliers: [
    {
      id: 'rp-mind-can-go-a',
      name: 'Mind Can Go · Classic',
      group: 'Quotes',
      description: 'AI quote — soft vertical lines, Manrope display',
      width: 1080,
      height: 1700,
      filename: 'royal-prince-mind-can-go-a',
      Component: MindCanGoQuote,
      props: {
        width: 1080,
        height: 1700,
        variant: 'lines-a',
        headline1: 'AI is',
        headline2Lead: 'as',
        headline2Muted: 'far',
        headline3: 'your mind can go.',
      },
    },
    {
      id: 'rp-mind-can-go-b',
      name: 'Mind Can Go · Vision',
      group: 'Quotes',
      description: 'AI quote — grid lines, Syne display',
      width: 900,
      height: 1700,
      filename: 'royal-prince-mind-can-go-b',
      Component: MindCanGoQuote,
      props: {
        width: 900,
        height: 1700,
        variant: 'lines-b',
        headline1: 'AI goes',
        headline2Lead: 'where your',
        headline2Muted: 'vision',
        headline3: 'dares to reach.',
      },
    },
    {
      id: 'rp-mind-can-go-b-square',
      name: 'Mind Can Go · Vision 1080',
      group: 'Quotes',
      description: 'Square AI quote — black void, grid lines, Syne display',
      width: 1080,
      height: 1080,
      filename: 'royal-prince-mind-can-go-b-square',
      Component: MindCanGoQuote,
      props: {
        width: 1080,
        height: 1080,
        variant: 'lines-b',
        headline1: 'AI goes',
        headline2Lead: 'where your',
        headline2Muted: 'vision',
        headline3: 'dares to reach.',
      },
    },
    {
      id: 'rp-mind-can-go-c',
      name: 'Mind Can Go · Superpowers',
      group: 'Quotes',
      description: 'AI quote — angled lines, DM Sans display',
      width: 1080,
      height: 1600,
      filename: 'royal-prince-mind-can-go-c',
      Component: MindCanGoQuote,
      props: {
        width: 1080,
        height: 1600,
        variant: 'lines-c',
        headline1: 'AI gives',
        headline2Lead: 'your mind',
        headline2Muted: 'super',
        headline3: 'powers to build.',
      },
    },
    {
      id: 'rp-mind-can-go-d',
      name: 'Mind Can Go · Horizon',
      group: 'Quotes',
      description: 'AI quote — vertical lines with glow, Manrope display',
      width: 900,
      height: 1600,
      filename: 'royal-prince-mind-can-go-d',
      Component: MindCanGoQuote,
      props: {
        width: 900,
        height: 1600,
        variant: 'lines-d',
        headline1: 'AI meets',
        headline2Lead: 'you at the',
        headline2Muted: 'edge',
        headline3: 'of what you imagine.',
      },
    },
    {
      id: 'rp-mind-can-go-gray-a',
      name: 'Mind Can Go · Classic Gray',
      group: 'Quotes · Gray',
      description: 'Square AI quote — gray void, vertical lines',
      width: 1080,
      height: 1080,
      filename: 'royal-prince-mind-can-go-gray-a',
      Component: MindCanGoQuote,
      props: {
        width: 1080,
        height: 1080,
        variant: 'lines-a',
        useGrayBg: true,
        headline1: 'AI is',
        headline2Lead: 'as',
        headline2Muted: 'far',
        headline3: 'your mind can go.',
      },
    },
    {
      id: 'rp-mind-can-go-gray-b',
      name: 'Mind Can Go · Vision Gray',
      group: 'Quotes · Gray',
      description: 'Square AI quote — grid lines, gray void',
      width: 1080,
      height: 1080,
      filename: 'royal-prince-mind-can-go-gray-b',
      Component: MindCanGoQuote,
      props: {
        width: 1080,
        height: 1080,
        variant: 'lines-b',
        useGrayBg: true,
        headline1: 'AI goes',
        headline2Lead: 'where your',
        headline2Muted: 'vision',
        headline3: 'dares to reach.',
      },
    },
    {
      id: 'rp-mind-can-go-gray-c',
      name: 'Mind Can Go · Super Gray',
      group: 'Quotes · Gray',
      description: 'Square AI quote — angled lines, gray void',
      width: 1080,
      height: 1080,
      filename: 'royal-prince-mind-can-go-gray-c',
      Component: MindCanGoQuote,
      props: {
        width: 1080,
        height: 1080,
        variant: 'lines-c',
        useGrayBg: true,
        headline1: 'AI gives',
        headline2Lead: 'your mind',
        headline2Muted: 'super',
        headline3: 'powers to build.',
      },
    },
    {
      id: 'rp-mind-can-go-gray-d',
      name: 'Mind Can Go · Horizon Gray',
      group: 'Quotes · Gray',
      description: 'Square AI quote — vertical lines, gray glow',
      width: 1080,
      height: 1080,
      filename: 'royal-prince-mind-can-go-gray-d',
      Component: MindCanGoQuote,
      props: {
        width: 1080,
        height: 1080,
        variant: 'lines-d',
        useGrayBg: true,
        headline1: 'AI meets',
        headline2Lead: 'you at the',
        headline2Muted: 'edge',
        headline3: 'of what you imagine.',
      },
    },
    {
      id: 'rp-era-possible-black',
      name: 'Era Possible · Black',
      group: 'Quotes',
      description: 'Square AI quote — black void, era where everything is possible',
      width: 1080,
      height: 1080,
      filename: 'royal-prince-era-possible-black',
      Component: MindCanGoQuote,
      props: {
        width: 1080,
        height: 1080,
        variant: 'lines-a',
        headline1: 'We are now',
        headline2Lead: 'in an era where',
        headline2Muted: 'everything',
        headline3: 'is possible.',
      },
    },
    {
      id: 'rp-era-possible-gray',
      name: 'Era Possible · Gray',
      group: 'Quotes · Gray',
      description: 'Square AI quote — light gray void, era where everything is possible',
      width: 1080,
      height: 1080,
      filename: 'royal-prince-era-possible-gray',
      Component: MindCanGoQuote,
      props: {
        width: 1080,
        height: 1080,
        variant: 'lines-a',
        useGrayBg: true,
        headline1: 'We are now',
        headline2Lead: 'in an era where',
        headline2Muted: 'everything',
        headline3: 'is possible.',
      },
    },
    {
      id: 'rp-ai-superpowers-grotesk',
      name: 'AI Superpowers · Grotesk',
      group: 'Quotes · Grotesk',
      description: 'Black void AI quote — Clash / Neue grotesk display',
      width: 1080,
      height: 1350,
      filename: 'royal-prince-ai-superpowers-grotesk',
      Component: MindCanGoQuote,
      props: {
        width: 1080,
        height: 1350,
        variant: 'grotesk-a',
        headline1: 'AI gives',
        headline2Lead: 'your mind',
        headline2Muted: 'super',
        headline3: 'powers to build.',
      },
    },
    {
      id: 'rp-era-possible-grotesk-gray',
      name: 'Era Possible · Grotesk Gray',
      group: 'Quotes · Grotesk',
      description: 'Gray void era quote — grotesk display stack',
      width: 1080,
      height: 1350,
      filename: 'royal-prince-era-possible-grotesk-gray',
      Component: MindCanGoQuote,
      props: {
        width: 1080,
        height: 1350,
        variant: 'grotesk-b',
        useGrayBg: true,
        headline1: 'We are now',
        headline2Lead: 'in an era where',
        headline2Muted: 'everything',
        headline3: 'is possible.',
      },
    },
    {
      id: 'rp-mind-future-grotesk',
      name: 'Mind Future · Grotesk',
      group: 'Quotes · Grotesk',
      description: 'Black void quote — your mind builds the future, with soft abstract orbits',
      width: 1080,
      height: 1350,
      filename: 'royal-prince-mind-future-grotesk',
      Component: MindCanGoQuote,
      props: {
        width: 1080,
        height: 1350,
        variant: 'grotesk-c',
        headline1: 'Your mind is',
        headline2Lead: 'the first place',
        headline2Muted: 'you build',
        headline3: 'the future.',
      },
    },
    {
      id: 'rp-consistency-engine-grotesk',
      name: 'Consistency Engine · Grotesk',
      group: 'Quotes · Grotesk',
      description: 'Gray void quote — consistency as a quiet engine, with angled line texture',
      width: 1080,
      height: 1350,
      filename: 'royal-prince-consistency-engine-grotesk',
      Component: MindCanGoQuote,
      props: {
        width: 1080,
        height: 1350,
        variant: 'grotesk-d',
        useGrayBg: true,
        headline1: 'Consistency is',
        headline2Lead: 'a quiet engine',
        headline2Muted: 'that compounds',
        headline3: 'loudly over time.',
      },
    },
    {
      id: 'rp-clarity-steps-grotesk',
      name: 'Clarity Steps · Grotesk',
      group: 'Quotes · Grotesk',
      description: 'Black void quote — clarity turns impossible into simple steps, with subtle grid glow',
      width: 1080,
      height: 1350,
      filename: 'royal-prince-clarity-steps-grotesk',
      Component: MindCanGoQuote,
      props: {
        width: 1080,
        height: 1350,
        variant: 'grotesk-e',
        headline1: 'Clarity turns',
        headline2Lead: 'impossible problems',
        headline2Muted: 'into simple',
        headline3: 'steps you can take.',
      },
    },
  ],
})
